---
title: "Research"
execute: 
  echo: false
  message: false
  warning: false
format: html 
toc: true
toc-location: left
---
I have worked in multiple labs and collaborated with researchers from diverse discipline. 
My work centers on wearable sensing, designing and analyzing data from portable devices that measure physiological signals in real time. I’m particularly interested in running AI models on embedded hardware, bridging the gap between sensing and intelligent on-device computation.

I also conduct computational research using high-performance computing (HPC) to analyze large-scale datasets such as genomics, EHR, and spectroscopy data. 

My Ph.D. thesis involves an integrated framework that addresses two critical challenges in biomedical AI: data scarcity and poor generalization. My hypothesis is that by combining domain knowledge, hardware–AI co-design, and generative models, we can create synthetic biomedical data to enhance sensing + modeling.
My main application is a continuation of my Master's work : A non-invasive wearable Hydration Tracking device.

You can explore these projects in more detail on my [Projects Page](projects.qmd).
<!-- Remove margin under list items -->

<style>
ol {
    margin-bottom: 5px;
}
p {
  margin: 5px 0 0 0;
}
</style>

```{r setup}
source("_common.R")

# Update local copy of "pubs" Google sheet
# write_csv(get_pubs(), here::here('content', 'pubs.csv'))

# Get local copy of pubs
# pubs <- read_csv(here::here('content', 'pubs.csv'))

# Get pubs from Google sheet
pubs <- get_pubs()
```


**Research focus**

- Wearables & Digital Biomarkers  
- Computational Spectroscopy & Biomedical Sensing 
- Neurotechnology & Brain–Computer Interfaces  
- Computational Genomics & Bioinformatics
- Clinical Data Science (EHR/omics; robust, reproducible pipelines)

<center>

[View my full CV here](cv/nazim_hub_resume_202511.pdf)

`r htmltools::HTML(paste0(icon_link(icon = "ai ai-google-scholar", text = "Google Scholar", url  = "https://scholar.google.com/citations?view_op=list_works&hl=en&user=f7QBAtEAAAAJ"), icon_link(icon = "ai ai-orcid", text = "ORCID", url  = "https://orcid.org/0009-0006-8380-9818"), icon_link(icon = "ai ai-researchgate", text = "Research Gate", url = "https://www.researchgate.net/profile/Nazim-Belabbaci")))`


