project:
  type: website
  output-dir: ../docs/projects/wearable-hydration  # <- puts files in the published docs/
  execute-dir: project

website:
  title: "HydroTrack: Real-Time Hydration Monitoring"
  navbar:
    left:
      - href: index.qmd
        text: Overview
  page-footer:
    left: "© 2025 Nazim A. Belabbaci"

format:
  html:
    theme: cosmo
    toc: true
