name: Render and Publish Quarto Site

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # Needed so the action can push to gh-pages
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: true   

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # If you don't use R/Python execution in your .qmd, this is enough.
      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish to GitHub Pages (gh-pages)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
